spring:
  application:
    name: gateway-platform
  cloud:
    gateway:
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 返回的资源共享给请求来源
            allowed-origins:
              - "http://localhost:8080"
              - "http://shop.z.mukewang.com:8080"
              - "http://center.z.mukewang.com:8080"
              - "http://shop.z.mukewang.com"
              - "http://center.z.mukewang.com"
              - "*"
            # 比如cookie, authorization之类的认证信息
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            # 表示Options可以在浏览器缓存多长时间
            max-age: 600
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
        # routs 在代码里面配置
  redis:
    host: 192.168.3.26
    port: 6379
    database: 0
    password: 123456
  main:
    allow-bean-definition-overriding: true
  # 链路追踪
  zipkin:
    discovery-client-enabled: true
    base-url: http://ZIPKIN-SERVER/
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1

server:
  port: 20004

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.26:20000/eureka/

## 开启所有actuator-endpoint
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always