spring:
  application:
    name: gateway-platform
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
        # routs 在代码里面配置
  redis:
    host: 192.168.3.26
    port: 6379
    database: 0
    password: 123456
  main:
    allow-bean-definition-overriding: true

server:
  port: 20004

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.26:20000/eureka/

## 开启所有actuator-endpoint
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always