server:
  port: 20003

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        # 属性重载，git上的配置将被覆盖
        overrides:
          test: localConfigFileValue
        git:
          uri: https://gitee.com/pangzl/foodie-cloud-config.git
          force-pull: true
          # 将配置文件放到接入方服务名称对应文件夹下面
          search-paths: '{application}'
          # 可为仓库设置用户名密码以加密
          # username:
          # password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.26:20000/eureka/

## 开启所有actuator-endpoint
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always