server:
  port: 10003

spring:
  datasource:
    # 新版本必须指定是否使用ssl连接：&useSSL=false
    url: jdbc:mysql://192.168.3.26:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  redis:
    # 单节点配置方式
    # database设置使用哪个数据库，在redis-cli中使用命令select 1来使用该库
    database: 0
    host: 192.168.3.26
    port: 6379
    password: 123456
    # sentinel 哨兵配置方式
#    database: 1
#    password: 123456
#    sentinel:
#      master: mymaster-nick-name
      # 注意端口为哨兵进程的端口
#      nodes: 192.168.3.26:26379,192.168.3.17:26379,192.168.3.27:26379
    # cluster 集群配置方式
#    password: 123456
#    cluster:
#      nodes: 192.168.3.16:6379,192.168.3.17:6379,192.168.3.26:6379,192.168.3.27:6379
  # 链路追踪
  zipkin:
    discovery-client-enabled: true
    base-url: http://ZIPKIN-SERVER/
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
  # stream 延迟消息配置
  cloud:
    stream:
      bindings:
        order-status-consumer:
          destination: order-status-topic
          group: order-status-group
        order-status-producer:
          destination: order-status-topic
      rabbit:
        bindings:
          order-status-producer:
            producer:
              delayed-exchange: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 开启查询SQL日志

# Ribbon全局配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000

# Ribbon指定服务配置超时判定，优先级高于全局配置
foodie-user-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxAutoRetries: 2                      # 每台机器最大重试次数
    MaxAutoRetriesNextServer: 2            # 可以再重试几台机器
    OkToRetryOnAllOperations: true         # 在所有HTTP Method进行重试 默认为false，仅在GET类型上重试。谨慎开启，要确保接口实现幂等性

# Feign的超时配置，优先级高于Ribbon
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 5000
      # 指定服务超时配置，优先级高于全局配置
      foodie-user-service:
        connectTimeout: 1000
        readTimeout: 5000
# 开启actuator端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security: false

hystrix:
  command:
    # 有的属性是默认值，写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000
