spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true

server:
  port: 20005

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.26:20000/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
